### ISSUE TITLE
Error handling log messages with exceptions

### ISSUE THREAD

**Issue by Felk** [jlnpinheiro/logger-discord-provider#1]
I am trying out this logging sink and encountered a problem logging errors with exceptions. I simply attempted this:

```c#
_logger.LogError(new Exception(), "Testexception!");
```

And the result was ":skull: Error: An error occurred in sending the message: {"embeds": ["0"]} - HTTP status code 400 - BadRequest":

![image](https://user-images.githubusercontent.com/1996138/105554042-dcc4bd00-5d06-11eb-89ef-95df2620846d.png)

with this content:

```json
{
  "username": null,
  "avatar_url": null,
  "content": ":skull: **Error**: Testexception!",
  "tts": false,
  "embeds": [
    {
      "color": 14431557,
      "author": null,
      "title": null,
      "url": null,
      "description": "**Exception of type 'System.Exception' was thrown.**",
      "fields": [
        {
          "name": "Exception type",
          "value": "System.Exception",
          "inline": false
        },
        {
          "name": "Source",
          "value": null,
          "inline": false
        }
      ],
      "thumbnail": null,
      "image": null,
      "footer": null
    }
  ]
}
```

I am running .NET 5 on windows. I created the logger factory as follows:

```C#
LoggerFactory.Create(builder =>
{
    builder.AddConsole().SetMinimumLevel(LogLevel.Debug);
    if (baseConfig.LogPath != null) builder.AddFile(Path.Combine(baseConfig.LogPath, "tpp-{Date}.log"));
    var options = new DiscordLoggerOptions("https://discord.com/api/webhooks/...../.....");
    builder.AddProvider(new DiscordLoggerProvider(options)).SetMinimumLevel(LogLevel.Warning);
});
```

**Comment by Felk** [comment]
The issue was me just creating an exception using `new Exception()`, which are not representative for actual exceptions

**Comment by jlnpinheiro** [comment]
I hope the component is useful! 👍

**Comment by MarshMello0** [comment]
I feel like it is valid to make your own exceptions with `new Exception()` in a production enviroment. Even this libary does it. So I created a PR which catches stops the error from happening.
