### ISSUE TITLE
Consider using a background thread for sending log messages

### ISSUE THREAD

**Issue by alexrp** [jlnpinheiro/logger-discord-provider#2]
Sending messages to Discord directly in the `DiscordLogger.Log<TState>()` method will block any thread that does logging. This isn't great in general, but it's particularly bad because the method can't use `async`/`await`. This can cause thread pool starvation.

Other loggers generally use a background thread + a concurrent queue to handle log messages for this reason.

Example: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs

(Side note: `task.GetAwaiter().GetResult()` is pretty much always better than `task.Wait()`.)

**Comment by jlnpinheiro** [comment]
Hi @alexrp !
Thanks for your message!
Could you send me a PR with your sugestions?

**Comment by jlnpinheiro** [comment]
No sugestions = issue closed!
